### ISSUE TITLE
Filename collection

### ISSUE THREAD

**Issue by emmelleppi** [nidorx/matcaps#1]
Hello! First of all thank you for this amazing collection :)

I wanted to ask you if it is possible to have a json file (or any other format) containing all the filenames of the matcaps.

In this way we could take the images directly from your github randomly, without having to download the single images or necessarily choose a specific one.

It would be enough to concatenate the url in a similar way

```https://raw.githubusercontent.com/nidorx/matcaps/master/${format}/${filename}-${format}px.png```

Thank you!

**Comment by nidorx** [comment]
I'll add, it's something simple!
