### ISSUE TITLE
Interactive Gallery

### ISSUE THREAD

**Issue by MAKIO135** [nidorx/matcaps#2]
Not an issue here, more a suggestion for an example, I made this tool to explore the different materials in a friendly way:  
https://next.observablehq.com/@makio135/matcaps

(Urls are pointing to https://makio135.com/matcaps/… cause I had to fork the repo to access them through Github pages, and I'm using Github pages to serve my website)

Anyway, thanks for this repo :)

**Comment by nidorx** [comment]
Thanks @MAKIO135, I updated README.md with the link to the gallery. Excellent work you did there.

Sorry for the delay, I was out of the matrix for a few weeks :(

**Comment by MAKIO135** [comment]
Wow! So glad you added it. No worry for the delay and thanks once again for your work 🙏
